### ISSUE TITLE
UI comments

### ISSUE THREAD

**Issue by nomis52** [OpenLightingProject/rdm-app#11]
Comments / Suggestions from #10 

- I'd removed the "RDM Manufacturer Library" in the top left, since there isn't really a 'Home' page for this site.
- In the manufacturer list, it would be good to be able to filter by id. Right now I always just Control-F to lookup the manufacturer id
- Also on the manufacturer list, it may be worth breaking out the decimal and hex values into separate columns.
- On the About page, the heading are rather compacted. I think a bit more whitespace would make it easier to read.
- On the device page, some more whitespace around the devices would be good, see screenshot. The other pages (Splitters, Software etc.) have a good amount of spacing. ![screen shot 2015-04-05 at 9 15 21 am](https://cloud.githubusercontent.com/assets/4355332/6997560/663dbd9a-db74-11e4-97ff-529449627d7b.png)

- At least on my machine, whenever there is a select list followed by a button, the two are joined, eg http://rdm.bewaar.me/model/manufacturer?manufacturer=8482 . See attached screenshot
![screen shot 2015-04-05 at 9 16 39 am](https://cloud.githubusercontent.com/assets/4355332/6997567/94f6935a-db74-11e4-82a7-5869d2d582ce.png)

- On the devices search by .... pages, can you make the table fill the entire width of the screen. 
![screen shot 2015-04-05 at 9 18 53 am](https://cloud.githubusercontent.com/assets/4355332/6997575/cba96cd8-db74-11e4-8427-1a09350d5e52.png)

**Comment by daveol** [comment]
> - I'd removed the "RDM Manufacturer Library" in the top left, since there isn't really a 'Home' page for this site.

The link or the whole thing?
> - In the manufacturer list, it would be good to be able to filter by id. Right now I always just Control-F to lookup the manufacturer id
- Also on the manufacturer list, it may be worth breaking out the decimal and hex values into separate columns.

I will look into these. 
> - On the About page, the heading are rather compacted. I think a bit more whitespace would make it easier to read.

I'll probably make it look like markdown
> - On the device page, some more whitespace around the devices would be good, see screenshot. The other pages (Splitters, Software etc.) have a good amount of spacing. 

[solved](http://http://rdm.bewaar.me/)
> - At least on my machine, whenever there is a select list followed by a button, the two are joined, eg http://rdm.bewaar.me/model/manufacturer?manufacturer=8482 . See attached screenshot

I'll probably use [labels](http://getbootstrap.com/css/#forms-inline) instead of [add-ons](http://getbootstrap.com/components/#input-groups-basic) form now on, however this is weird and probably a issue in bootstrap.
> - On the devices search by .... pages, can you make the table fill the entire width of the screen. 

[also solved](http://rdm.bewaar.me/model/manufacturer?manufacturer=31344)

**Comment by daveol** [comment]
> - I'd removed the "RDM Manufacturer Library" in the top left, since there isn't really a 'Home' page for this site.

[done](http://rdm.bewaar.me/)
> - In the manufacturer list, it would be good to be able to filter by id. Right now I always just Control-F to lookup the manufacturer id
> - Also on the manufacturer list, it may be worth breaking out the decimal and hex values into separate columns.

This will be added later seeing as it's more of a feature request that is nice to have

**Comment by daveol** [comment]
I think this can be closed since the unresolved points are already in #14

**Comment by nomis52** [comment]
Agreed
