### ISSUE TITLE
New UI Bugs

### ISSUE THREAD

**Issue by nomis52** [OpenLightingProject/rdm-app#13]
These are the blockers, I've filed a separate bug with the nice-to-haves.

Parameters Page
 - Some PIDs are showing up as not having GET or SET. Compare http://rdm.openlighting.org/pid/id?id=0x8000 vs http://rdm.bewaar.me/pid/id?id=0x8000 .  Actually it looks like the SET column is using the data from the GET column.

Controllers
 - Searching by manufacturer results in an error. For example if I click 'Controllers', then click 'Search' I get http://rdm.bewaar.me/controller/browse?manufacturer=16708 which is a 500. The same URL loads on the main site so this may be a data issue?
 - Clicking on a picture of a controller doesn't do anything.

Software / Ethernet Nodes / Splitters
 - Same 2 bugs as Controllers

**Comment by daveol** [comment]
> - Some PIDs are showing up as not having GET or SET. Compare http://rdm.openlighting.org/pid/id?id=0x8000 vs http://rdm.bewaar.me/pid/id?id=0x8000 . Actually it looks like the SET column is using the data from the GET column.

fixed. was probably a copy paste error..

> - Searching by manufacturer results in an error. For example if I click 'Controllers', then click 'Search' I get http://rdm.bewaar.me/controller/browse?manufacturer=16708 which is a 500. The same URL loads on the main site so this may be a data issue?

It was a index issue I believe.... all I know is that I reloaded everything into the database and it worked again.

> - Clicking on a picture of a controller doesn't do anything.

Or on the title... but that's fixed now.

**Comment by nomis52** [comment]
Confirmed fixed.
