### ISSUE TITLE
Manufacturer PIDs

### ISSUE THREAD

**Issue by fxedel** [OpenLightingProject/rdm-app#133]
Hey, I've just downloaded [ELC Lighting's Fixture Library](https://www.elclighting.com/products/fixture-library/) in which I accidentally found a file containing many manufacturers with their PIDs. The PID values are different than in rdm.openlighting.org, but the names are the same.

Don't know if this is a help, but I saw it and wanted to share it with you.

[ManufacturerSpecificPIDs.xml.txt](https://github.com/OpenLightingProject/rdm-app/files/1389071/ManufacturerSpecificPIDs.xml.txt)

**Comment by peternewman** [comment]
Why do you think the IDs are different?

**Comment by fxedel** [comment]
Correct. I must have mixed something up with the ids. All the better – you can use this as a source of new data, if there are new manufacturers.

**Comment by peternewman** [comment]
Sorry @fxedel I think you've missed my point. In terms of the manufacturer IDs themselves at least, there is only one source of data, the ESTA Technical Standards Programme is the equivalent of IANA for RDM, if it's not registered with them, your ID isn't valid. They list the IDs on their site, and we use that data to make our manufacturer list:
https://github.com/OpenLightingProject/rdm-app/blob/master/tools/make_manufacturer_data.sh#L43

Separate to that, manufacturers can expose their own custom PIDs to do special things that aren't in the standard. There is no central registry of these, we try our best to gather them, and one or two commercial companies try to as well. Theoretically ELC could be buying from them, or gathering themselves (in which case I don't know where we'd sit from a copyright perspective, is that their work or data etc). However based on the wording and variables etc, I strongly suspect their data is just an XML version of our file, so there's probably nothing new to get from there anyway.

**Comment by fxedel** [comment]
Ok, I didn't knew from where you get your data. Thanks for the answer.
