### ISSUE TITLE
Minor tweaks to the Device info page

### ISSUE THREAD

**Issue by nomis52** [OpenLightingProject/rdm-app#15]
Example: http://rdm.bewaar.me/model/display?manufacturer=31344&model=1

- Can you reduce the width of the "Software Version:" drop down so it doesn't span the entire page
- In the Supports Recording & Supports Min/Max, can you use the tick icon rather than 'true / false' . I think false can just be left blank, rather than using a cross.

**Comment by daveol** [comment]
fixed
