### ISSUE TITLE
Add a CSS Linter

### ISSUE THREAD

**Issue by peternewman** [OpenLightingProject/rdm-app#266]
To catch issues like:

> I guess this file is not preprocessed since it's in the `static` folder? Then you should use `/* … */` for comments, CSS doesn't support `//`.

_Originally posted by @FloEdelmann in https://github.com/OpenLightingProject/rdm-app/pull/265#discussion_r361483328_

**Comment by FloEdelmann** [comment]
There are basically two possible options:

1. [Stylelint](https://stylelint.io/) ([GitHub](https://github.com/stylelint/stylelint))
2. [CSS Lint](http://csslint.net/) ([GitHub](https://github.com/CSSLint/csslint))

Stylelint is very flexible and has good defaults with the [stylelint-config-standard](https://github.com/stylelint/stylelint-config-standard), so it looks like the better choice to me. There is a good introductory [article on CSS Tricks](https://css-tricks.com/stylelint/).
