### ISSUE TITLE
Please push the queue in rdm.openlighting.org/admin

### ISSUE THREAD

**Issue by vanous** [OpenLightingProject/rdm-app#288]
Hi all,

any chance to push the queue of collector data in rdm.openlighting.org/admin?

cheers!

**Comment by peternewman** [comment]
Hi @vanous ,

Sorry I seem to have missed the notification emails.

I've pushed most of them through now.

Is it correct that the Viva Pro is now the Viva CMY:
http://rdm.openlighting.org/model/display?manufacturer=21075&model=203

**Comment by vanous** [comment]
Hi @peternewman 

thank you!

Yes, the Viva Pro was more of an internal name, the final version is what is the Viva CMY today.

Cheers

**Comment by peternewman** [comment]
Great, I'll close this then. Feel free to nudge us sooner if they haven't appeared.
