### ISSUE TITLE
Manufacturers list is out of date

### ISSUE THREAD

**Issue by peternewman** [OpenLightingProject/rdm-app#7]
Doesn't include e.g. 0x8383 @nightrune 's ID.
https://github.com/OpenLightingProject/rdm-app/blob/master/data/manufacturer_data.py

**Comment by peternewman** [comment]
Source from:
http://tsp.plasa.org/tsp/working_groups/CP/rdmids.php

Write a little script like the RDM bits in OLA.

**Comment by peternewman** [comment]
@nomis52 I'm pondering what do to about line endings for this, the existing file is DOS format; I'm guessing it doesn't need to be? Would you prefer normal Linux line endings like the other data files?

**Comment by nomis52** [comment]
Please remove the DOS line endings.

**Comment by peternewman** [comment]
https://github.com/OpenLightingProject/rdm-app/pull/8

**Comment by peternewman** [comment]
Code merged, just needs deploying please @nomis52 .

**Comment by nomis52** [comment]
Done

**Comment by peternewman** [comment]
Thanks @nomis52 . Closing this one then. We'll just have to remember to run the script every so often.
